# Nombre del alias para el certificado
alias=mycert

# Nombre del archivo del keystore donde se almacenará el certificado
keystore=mykeystore.jks

# Contraseña para proteger el keystore
storepass=changeit

# Contraseña para proteger la clave privada del certificado
keypass=changeit

# Distinguished Name (DN) para el certificado
dname="CN=My Name, OU=My Organizational Unit, O=My Organization, L=My City, ST=My State, C=My Country"

# Algoritmo para la clave del certificado
keyalg=RSA

# Tamaño de la clave
keysize=2048

# Validez del certificado en días
validity=3650
